{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 51,
   "id": "1001f4b2-6ae2-412a-aa7b-87664c79d568",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Import Pandas\n",
    "import pandas as pd\n",
    "\n",
    "#load in from CSV\n",
    "df = pd.read_csv('Dec15-21_Eataly_Schedule.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "id": "4e1dd73a-8140-4403-a6d3-de3392e217a7",
   "metadata": {},
   "outputs": [],
   "source": [
    "#drop all irrelevant rows at the top\n",
    "df = df.drop([0,2,3,4])\n",
    "\n",
    "#reset indexes\n",
    "df = df.reset_index(drop=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "id": "34385eee-7dc7-4517-b68b-d66757b3803f",
   "metadata": {},
   "outputs": [],
   "source": [
    "#rename the column names:\n",
    "df = df.rename(columns={'Unnamed: 0':'Name'})\n",
    "\n",
    "df = df.rename(columns={'Monday':'Monday_AM'})\n",
    "df = df.rename(columns={'Unnamed: 2':'Monday_PM'})\n",
    "\n",
    "df = df.rename(columns={'Tuesday':'Tuesday_AM'})\n",
    "df = df.rename(columns={'Unnamed: 4':'Tuesday_PM'})\n",
    "\n",
    "df = df.rename(columns={'Wednesday':'Wednesday_AM'})\n",
    "df = df.rename(columns={'Unnamed: 6':'Wednesday_PM'})\n",
    "\n",
    "df = df.rename(columns={'Thursday':'Thursday_AM'})\n",
    "df = df.rename(columns={'Unnamed: 8':'Thursday_PM'})\n",
    "\n",
    "df = df.rename(columns={'Friday':'Friday_AM'})\n",
    "df = df.rename(columns={'Unnamed: 10':'Friday_PM'})\n",
    "\n",
    "df = df.rename(columns={'Saturday':'Saturday_AM'})\n",
    "df = df.rename(columns={'Unnamed: 12':'Saturday_PM'})\n",
    "\n",
    "df = df.rename(columns={'Sunday':'Sunday_AM'})\n",
    "df = df.rename(columns={'Unnamed: 14':'Sunday_PM'})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "id": "2591ef71-675c-4033-b4da-552a01e9fae7",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['EVENTS',\n",
       " '14pax a la carte MDR 1pm-3pm, 13pax MDR a la carte 530pm-730pm',\n",
       " 'None',\n",
       " 'None',\n",
       " 'None',\n",
       " 'None',\n",
       " 'None',\n",
       " '26pax MDR family style 4pm-630pm, 15pax PDR family style 5pm-730pm',\n",
       " 'None',\n",
       " 'None',\n",
       " 'None',\n",
       " 'None',\n",
       " 'None',\n",
       " 'None',\n",
       " 'None']"
      ]
     },
     "execution_count": 54,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Clean up events row by replacing empty cells with 'none'\n",
    "df.iloc[0] = df.iloc[0].fillna(\"None\")\n",
    "\n",
    "#extract events as a list\n",
    "first_row_list = df.iloc[0].tolist()\n",
    "\n",
    "first_row_list\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "id": "b3322056-2fac-4b75-9a8d-10b026691391",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Name</th>\n",
       "      <th>Monday_AM</th>\n",
       "      <th>Monday_PM</th>\n",
       "      <th>Tuesday_AM</th>\n",
       "      <th>Tuesday_PM</th>\n",
       "      <th>Wednesday_AM</th>\n",
       "      <th>Wednesday_PM</th>\n",
       "      <th>Thursday_AM</th>\n",
       "      <th>Thursday_PM</th>\n",
       "      <th>Friday_AM</th>\n",
       "      <th>Friday_PM</th>\n",
       "      <th>Saturday_AM</th>\n",
       "      <th>Saturday_PM</th>\n",
       "      <th>Sunday_AM</th>\n",
       "      <th>Sunday_PM</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Mudasir Addow</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Ilia Belchevichen</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Alejandra Calderon</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "      <td>11:00</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Jaikaran Chugh</td>\n",
       "      <td>SET</td>\n",
       "      <td>415PM</td>\n",
       "      <td>SET</td>\n",
       "      <td>415PM</td>\n",
       "      <td>SET</td>\n",
       "      <td>415PM</td>\n",
       "      <td>SET</td>\n",
       "      <td>415PM</td>\n",
       "      <td>SET</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Diletta Di Toma</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>14:00</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Diana Duong</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>415PM 1st cut</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Daniel Herrera</td>\n",
       "      <td>REQ</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "      <td>OFF</td>\n",
       "      <td>SET</td>\n",
       "      <td>415PM</td>\n",
       "      <td>SET</td>\n",
       "      <td>415PM</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>SET</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "      <td>415PM</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>David Morillas</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>Akriti Kandel</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>430PM EVENT</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>Kiana Mercado</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>Hasaan Mohsin</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>Tibor Lorincz</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>Arafa Mutimba</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>415PM 1st cut</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>Alessia Moro</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>11:00</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>14:00</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>REQ</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>Falguni Patel</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>14:00</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>Jude Salcedo</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>14:00</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>Mac Sealby</td>\n",
       "      <td>SET</td>\n",
       "      <td>REQ</td>\n",
       "      <td>SET</td>\n",
       "      <td>REQ</td>\n",
       "      <td>SET</td>\n",
       "      <td>REQ</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "      <td>REQ</td>\n",
       "      <td>REQ</td>\n",
       "      <td>REQ</td>\n",
       "      <td>REQ</td>\n",
       "      <td>REQ</td>\n",
       "      <td>REQ</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>Tiger Wu</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>Esma Sari</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>14:00</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>Sahil Thapa</td>\n",
       "      <td>14:00</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>Sabrina Santos</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>Julaiti Xijaaiti</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>SET</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>SET</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>SET</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>Adrio Fattorini</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>Hailey Jang</td>\n",
       "      <td>SET</td>\n",
       "      <td>REQ</td>\n",
       "      <td>SET</td>\n",
       "      <td>REQ</td>\n",
       "      <td>SET</td>\n",
       "      <td>REQ</td>\n",
       "      <td>SET</td>\n",
       "      <td>REQ</td>\n",
       "      <td>SET</td>\n",
       "      <td>REQ</td>\n",
       "      <td>SET</td>\n",
       "      <td>415PM</td>\n",
       "      <td>SET</td>\n",
       "      <td>415PM</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>Maria Giugliano</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>11:00</td>\n",
       "      <td>415PM</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>Grivia Fernandes</td>\n",
       "      <td>SET</td>\n",
       "      <td>OFF</td>\n",
       "      <td>SET</td>\n",
       "      <td>530PM</td>\n",
       "      <td>11:00</td>\n",
       "      <td>530PM</td>\n",
       "      <td>SET</td>\n",
       "      <td>530PM</td>\n",
       "      <td>SET</td>\n",
       "      <td>OFF</td>\n",
       "      <td>SET</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>Joshua Kaanoi</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>SET</td>\n",
       "      <td>415PM</td>\n",
       "      <td>11:00</td>\n",
       "      <td>415PM</td>\n",
       "      <td>SET</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>SET</td>\n",
       "      <td>OFF</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>Ugurcan Kesman</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "      <td>SET</td>\n",
       "      <td>11:00</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>Franco Dagostino</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>11:00</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>14:00</td>\n",
       "      <td>OFF</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>Chloe Hand</td>\n",
       "      <td>OFF</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>11:00</td>\n",
       "      <td>415PM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>OFF</td>\n",
       "      <td>1015AM</td>\n",
       "      <td>OFF</td>\n",
       "      <td>14:00</td>\n",
       "      <td>OFF</td>\n",
       "      <td>14:00</td>\n",
       "      <td>OFF</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                  Name Monday_AM Monday_PM Tuesday_AM Tuesday_PM Wednesday_AM  \\\n",
       "0        Mudasir Addow    1015AM       OFF     1015AM        OFF       1015AM   \n",
       "1    Ilia Belchevichen       OFF       OFF     1015AM        OFF       1015AM   \n",
       "2   Alejandra Calderon       SET       SET        SET        SET        11:00   \n",
       "3       Jaikaran Chugh       SET     415PM        SET      415PM          SET   \n",
       "4      Diletta Di Toma       OFF       OFF        OFF      415PM        14:00   \n",
       "5          Diana Duong       SET       SET        SET        SET          SET   \n",
       "6       Daniel Herrera       REQ       SET        SET        OFF          SET   \n",
       "7       David Morillas       OFF     415PM        OFF      415PM          OFF   \n",
       "8        Akriti Kandel       OFF     415PM        OFF        OFF          OFF   \n",
       "9        Kiana Mercado       OFF     415PM        OFF        OFF          OFF   \n",
       "10       Hasaan Mohsin       OFF     415PM     1015AM        OFF       1015AM   \n",
       "11       Tibor Lorincz    1015AM       OFF     1015AM        OFF       1015AM   \n",
       "12       Arafa Mutimba    1015AM       OFF     1015AM        OFF          OFF   \n",
       "13        Alessia Moro       OFF       OFF        OFF        OFF        11:00   \n",
       "14       Falguni Patel       OFF     415PM        OFF      415PM          OFF   \n",
       "15        Jude Salcedo       OFF     415PM        OFF      415PM          OFF   \n",
       "16          Mac Sealby       SET       REQ        SET        REQ          SET   \n",
       "17            Tiger Wu       OFF       OFF        OFF        OFF       1015AM   \n",
       "18           Esma Sari    1015AM       OFF      14:00        OFF       1015AM   \n",
       "19         Sahil Thapa     14:00       OFF        OFF      415PM          OFF   \n",
       "20      Sabrina Santos       OFF     415PM     1015AM        OFF       1015AM   \n",
       "21    Julaiti Xijaaiti       OFF       OFF     1015AM        OFF       1015AM   \n",
       "22     Adrio Fattorini    1015AM       OFF     1015AM        OFF          OFF   \n",
       "23         Hailey Jang       SET       REQ        SET        REQ          SET   \n",
       "24     Maria Giugliano    1015AM       OFF        OFF        OFF        11:00   \n",
       "25    Grivia Fernandes       SET       OFF        SET      530PM        11:00   \n",
       "26       Joshua Kaanoi    1015AM       OFF        SET      415PM        11:00   \n",
       "27      Ugurcan Kesman       SET       SET        SET        SET        11:00   \n",
       "28    Franco Dagostino    1015AM       OFF        OFF      415PM        11:00   \n",
       "29          Chloe Hand       OFF     415PM        OFF        OFF        11:00   \n",
       "\n",
       "   Wednesday_PM Thursday_AM  Thursday_PM Friday_AM Friday_PM Saturday_AM  \\\n",
       "0           OFF      1015AM          OFF    1015AM       OFF         SET   \n",
       "1           OFF      1015AM          OFF       OFF     415PM         OFF   \n",
       "2           SET         SET        415PM       OFF     415PM         OFF   \n",
       "3         415PM         SET        415PM       SET     415PM         OFF   \n",
       "4           OFF      1015AM          OFF    1015AM       OFF      1015AM   \n",
       "5           SET         SET          SET       SET       SET         SET   \n",
       "6         415PM         SET        415PM    1015AM       SET      1015AM   \n",
       "7           OFF         OFF          OFF    1015AM       OFF      1015AM   \n",
       "8           OFF         OFF  430PM EVENT       OFF     415PM         OFF   \n",
       "9           OFF         OFF        415PM       OFF     415PM         OFF   \n",
       "10          OFF         OFF          OFF       OFF     415PM         OFF   \n",
       "11          OFF         OFF          OFF       OFF     415PM         OFF   \n",
       "12          OFF         OFF          OFF    1015AM       OFF      1015AM   \n",
       "13        415PM         OFF        415PM       OFF     415PM       14:00   \n",
       "14          OFF         OFF        415PM     14:00       OFF         OFF   \n",
       "15          OFF       14:00          OFF       OFF     415PM         OFF   \n",
       "16          REQ         SET          SET       REQ       REQ         REQ   \n",
       "17          OFF      1015AM          OFF    1015AM       OFF      1015AM   \n",
       "18          OFF         OFF        415PM       OFF       OFF      1015AM   \n",
       "19          OFF         OFF          OFF    1015AM       OFF      1015AM   \n",
       "20          OFF      1015AM          OFF       OFF       OFF         OFF   \n",
       "21          OFF      1015AM          OFF       OFF       SET      1015AM   \n",
       "22          OFF      1015AM          OFF       OFF     415PM         OFF   \n",
       "23          REQ         SET          REQ       SET       REQ         SET   \n",
       "24        415PM      1015AM          OFF    1015AM       OFF         OFF   \n",
       "25        530PM         SET        530PM       SET       OFF         SET   \n",
       "26        415PM         SET        415PM       OFF       OFF      1015AM   \n",
       "27        415PM         OFF        415PM       OFF     415PM      1015AM   \n",
       "28        415PM         OFF          OFF    1015AM       OFF         OFF   \n",
       "29        415PM         OFF          OFF    1015AM       OFF       14:00   \n",
       "\n",
       "      Saturday_PM Sunday_AM      Sunday_PM  \n",
       "0             SET       SET            SET  \n",
       "1             OFF    1015AM            OFF  \n",
       "2           415PM       SET            SET  \n",
       "3             OFF       OFF            OFF  \n",
       "4             OFF       OFF            OFF  \n",
       "5             SET    1015AM  415PM 1st cut  \n",
       "6             SET       SET          415PM  \n",
       "7             OFF    1015AM            OFF  \n",
       "8           415PM       OFF          415PM  \n",
       "9           415PM       OFF          415PM  \n",
       "10          415PM       OFF            OFF  \n",
       "11          415PM       OFF            OFF  \n",
       "12  415PM 1st cut       OFF          415PM  \n",
       "13            OFF    1015AM            REQ  \n",
       "14          415PM       OFF            OFF  \n",
       "15          415PM       OFF            OFF  \n",
       "16            REQ       REQ            REQ  \n",
       "17            OFF    1015AM            OFF  \n",
       "18            OFF       OFF            OFF  \n",
       "19            OFF    1015AM            OFF  \n",
       "20            OFF    1015AM            OFF  \n",
       "21            SET    1015AM            SET  \n",
       "22            OFF    1015AM            OFF  \n",
       "23          415PM       SET          415PM  \n",
       "24            OFF    1015AM            OFF  \n",
       "25          415PM       OFF          415PM  \n",
       "26            OFF       SET            OFF  \n",
       "27            OFF       OFF          415PM  \n",
       "28            OFF     14:00            OFF  \n",
       "29            OFF     14:00            OFF  "
      ]
     },
     "execution_count": 55,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#remove events row\n",
    "df = df.drop(0)\n",
    "\n",
    "#reset indexes\n",
    "df = df.reset_index(drop=True)\n",
    "\n",
    "#replace all empty cells with 'OFF'\n",
    "df = df.fillna('OFF')\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 56,
   "id": "837a23e8-e275-4b98-b221-f5b3ea1cce0b",
   "metadata": {},
   "outputs": [],
   "source": [
    "df.to_csv('EXTRACT1')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 57,
   "id": "9a4c2295-f4ad-4565-b813-6a5c6e538baa",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']\n",
    "day_abbrev = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']\n",
    "\n",
    "# Function to clean and format time values\n",
    "def format_time(val):\n",
    "    val = str(val).strip()\n",
    "    if val in ['OFF', 'SET', 'REQ', 'nan', '']:\n",
    "        return val\n",
    "    return val\n",
    "\n",
    "# Build schedule data\n",
    "schedule_data = []\n",
    "\n",
    "for _, row in df.iterrows():\n",
    "    name = row['Name']\n",
    "    person_schedule = {'name': name}\n",
    "    \n",
    "    for day, abbrev in zip(days, day_abbrev):\n",
    "        am_col = f'{day}_AM'\n",
    "        pm_col = f'{day}_PM'\n",
    "        \n",
    "        am_val = str(row[am_col]).strip()\n",
    "        pm_val = str(row[pm_col]).strip()\n",
    "        \n",
    "        # Collect actual shift times\n",
    "        shifts = []\n",
    "        \n",
    "        if am_val not in ['OFF', 'SET', 'nan', '']:\n",
    "            shifts.append(format_time(am_val))\n",
    "        \n",
    "        if pm_val not in ['OFF', 'SET', 'nan', '']:\n",
    "            shifts.append(format_time(pm_val))\n",
    "        \n",
    "        # Determine shift status based on priority rules\n",
    "        if shifts:\n",
    "            # If either has a time, show the time(s)\n",
    "            if len(shifts) == 1:\n",
    "                person_schedule[abbrev] = shifts[0]\n",
    "            else:\n",
    "                person_schedule[abbrev] = shifts\n",
    "        elif am_val == 'SET' and pm_val == 'SET':\n",
    "            person_schedule[abbrev] = 'SET'\n",
    "        elif am_val == 'OFF' and pm_val == 'SET':\n",
    "            person_schedule[abbrev] = 'OFF'\n",
    "        elif am_val == 'SET' and pm_val == 'OFF':\n",
    "            person_schedule[abbrev] = 'OFF'\n",
    "        else:\n",
    "            person_schedule[abbrev] = 'OFF'\n",
    "    \n",
    "    schedule_data.append(person_schedule)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "id": "8471b90f-129d-4c85-b2ea-12d3f5767f9c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Schedule data saved to 'schedule_data.js'\n",
      "const scheduleData = [\n",
      "    { name: \"Mudasir Addow\", Mon: \"1015AM\", Tue: \"1015AM\", Wed: \"1015AM\", Thu: \"1015AM\", Fri: \"1015AM\", Sat: \"SET\", Sun: \"SET\" },\n",
      "    { name: \"Ilia Belchevichen\", Mon: \"OFF\", Tue: \"1015AM\", Wed: \"1015AM\", Thu: \"1015AM\", Fri: \"415PM\", Sat: \"OFF\", Sun: \"1015AM\" },\n",
      "    { name: \"Alejandra Calderon\", Mon: \"SET\", Tue: \"SET\", Wed: \"11:00\", Thu: \"415PM\", Fri: \"415PM\", Sat: \"415PM\", Sun: \"SET\" },\n",
      "    { name: \"Jaikaran Chugh\", Mon: \"415PM\", Tue: \"415PM\", Wed: \"415PM\", Thu: \"415PM\", Fri: \"415PM\", Sat: \"OFF\", Sun: \"OFF\" },\n",
      "    { name: \"Diletta Di Toma\", Mon: \"OFF\", Tue: \"415PM\", Wed: \"14:00\", Thu: \"1015AM\", Fri: \"1015AM\", Sat: \"1015AM\", Sun: \"OFF\" },\n",
      "    { name: \"Diana Duong\", Mon: \"SET\", Tue: \"SET\", Wed: \"SET\", Thu: \"SET\", Fri: \"SET\", Sat: \"SET\", Sun: [\"1015AM\", \"415PM 1st cut\"] },\n",
      "    { name: \"Daniel Herrera\", Mon: \"REQ\", Tue: \"OFF\", Wed: \"415PM\", Thu: \"415PM\", Fri: \"1015AM\", Sat: \"1015AM\", Sun: \"415PM\" },\n",
      "    { name: \"David Morillas\", Mon: \"415PM\", Tue: \"415PM\", Wed: \"OFF\", Thu: \"OFF\", Fri: \"1015AM\", Sat: \"1015AM\", Sun: \"1015AM\" },\n",
      "    { name: \"Akriti Kandel\", Mon: \"415PM\", Tue: \"OFF\", Wed: \"OFF\", Thu: \"430PM EVENT\", Fri: \"415PM\", Sat: \"415PM\", Sun: \"415PM\" },\n",
      "    { name: \"Kiana Mercado\", Mon: \"415PM\", Tue: \"OFF\", Wed: \"OFF\", Thu: \"415PM\", Fri: \"415PM\", Sat: \"415PM\", Sun: \"415PM\" },\n",
      "    { name: \"Hasaan Mohsin\", Mon: \"415PM\", Tue: \"1015AM\", Wed: \"1015AM\", Thu: \"OFF\", Fri: \"415PM\", Sat: \"415PM\", Sun: \"OFF\" },\n",
      "    { name: \"Tibor Lorincz\", Mon: \"1015AM\", Tue: \"1015AM\", Wed: \"1015AM\", Thu: \"OFF\", Fri: \"415PM\", Sat: \"415PM\", Sun: \"OFF\" },\n",
      "    { name: \"Arafa Mutimba\", Mon: \"1015AM\", Tue: \"1015AM\", Wed: \"OFF\", Thu: \"OFF\", Fri: \"1015AM\", Sat: [\"1015AM\", \"415PM 1st cut\"], Sun: \"415PM\" },\n",
      "    { name: \"Alessia Moro\", Mon: \"OFF\", Tue: \"OFF\", Wed: [\"11:00\", \"415PM\"], Thu: \"415PM\", Fri: \"415PM\", Sat: \"14:00\", Sun: [\"1015AM\", \"REQ\"] },\n",
      "    { name: \"Falguni Patel\", Mon: \"415PM\", Tue: \"415PM\", Wed: \"OFF\", Thu: \"415PM\", Fri: \"14:00\", Sat: \"415PM\", Sun: \"OFF\" },\n",
      "    { name: \"Jude Salcedo\", Mon: \"415PM\", Tue: \"415PM\", Wed: \"OFF\", Thu: \"14:00\", Fri: \"415PM\", Sat: \"415PM\", Sun: \"OFF\" },\n",
      "    { name: \"Mac Sealby\", Mon: \"REQ\", Tue: \"REQ\", Wed: \"REQ\", Thu: \"SET\", Fri: [\"REQ\", \"REQ\"], Sat: [\"REQ\", \"REQ\"], Sun: [\"REQ\", \"REQ\"] },\n",
      "    { name: \"Tiger Wu\", Mon: \"OFF\", Tue: \"OFF\", Wed: \"1015AM\", Thu: \"1015AM\", Fri: \"1015AM\", Sat: \"1015AM\", Sun: \"1015AM\" },\n",
      "    { name: \"Esma Sari\", Mon: \"1015AM\", Tue: \"14:00\", Wed: \"1015AM\", Thu: \"415PM\", Fri: \"OFF\", Sat: \"1015AM\", Sun: \"OFF\" },\n",
      "    { name: \"Sahil Thapa\", Mon: \"14:00\", Tue: \"415PM\", Wed: \"OFF\", Thu: \"OFF\", Fri: \"1015AM\", Sat: \"1015AM\", Sun: \"1015AM\" },\n",
      "    { name: \"Sabrina Santos\", Mon: \"415PM\", Tue: \"1015AM\", Wed: \"1015AM\", Thu: \"1015AM\", Fri: \"OFF\", Sat: \"OFF\", Sun: \"1015AM\" },\n",
      "    { name: \"Julaiti Xijaaiti\", Mon: \"OFF\", Tue: \"1015AM\", Wed: \"1015AM\", Thu: \"1015AM\", Fri: \"OFF\", Sat: \"1015AM\", Sun: \"1015AM\" },\n",
      "    { name: \"Adrio Fattorini\", Mon: \"1015AM\", Tue: \"1015AM\", Wed: \"OFF\", Thu: \"1015AM\", Fri: \"415PM\", Sat: \"OFF\", Sun: \"1015AM\" },\n",
      "    { name: \"Hailey Jang\", Mon: \"REQ\", Tue: \"REQ\", Wed: \"REQ\", Thu: \"REQ\", Fri: \"REQ\", Sat: \"415PM\", Sun: \"415PM\" },\n",
      "    { name: \"Maria Giugliano\", Mon: \"1015AM\", Tue: \"OFF\", Wed: [\"11:00\", \"415PM\"], Thu: \"1015AM\", Fri: \"1015AM\", Sat: \"OFF\", Sun: \"1015AM\" },\n",
      "    { name: \"Grivia Fernandes\", Mon: \"OFF\", Tue: \"530PM\", Wed: [\"11:00\", \"530PM\"], Thu: \"530PM\", Fri: \"OFF\", Sat: \"415PM\", Sun: \"415PM\" },\n",
      "    { name: \"Joshua Kaanoi\", Mon: \"1015AM\", Tue: \"415PM\", Wed: [\"11:00\", \"415PM\"], Thu: \"415PM\", Fri: \"OFF\", Sat: \"1015AM\", Sun: \"OFF\" },\n",
      "    { name: \"Ugurcan Kesman\", Mon: \"SET\", Tue: \"SET\", Wed: [\"11:00\", \"415PM\"], Thu: \"415PM\", Fri: \"415PM\", Sat: \"1015AM\", Sun: \"415PM\" },\n",
      "    { name: \"Franco Dagostino\", Mon: \"1015AM\", Tue: \"415PM\", Wed: [\"11:00\", \"415PM\"], Thu: \"OFF\", Fri: \"1015AM\", Sat: \"OFF\", Sun: \"14:00\" },\n",
      "    { name: \"Chloe Hand\", Mon: \"415PM\", Tue: \"OFF\", Wed: [\"11:00\", \"415PM\"], Thu: \"OFF\", Fri: \"1015AM\", Sat: \"14:00\", Sun: \"14:00\" }\n",
      "];\n"
     ]
    }
   ],
   "source": [
    "js_code = \"const scheduleData = [\\n\"\n",
    "\n",
    "for i, person in enumerate(schedule_data):\n",
    "    js_code += \"    { \"\n",
    "    items = []\n",
    "    for key, value in person.items():\n",
    "        if key == 'name':\n",
    "            items.append(f'name: \"{value}\"')\n",
    "        else:\n",
    "            if isinstance(value, list):\n",
    "                # Format array of shifts\n",
    "                formatted_shifts = ', '.join([f'\"{shift}\"' for shift in value])\n",
    "                items.append(f'{key}: [{formatted_shifts}]')\n",
    "            else:\n",
    "                items.append(f'{key}: \"{value}\"')\n",
    "    \n",
    "    js_code += \", \".join(items)\n",
    "    \n",
    "    if i < len(schedule_data) - 1:\n",
    "        js_code += \" },\\n\"\n",
    "    else:\n",
    "        js_code += \" }\\n\"\n",
    "\n",
    "js_code += \"];\"\n",
    "\n",
    "# Save to file\n",
    "with open('schedule_data.js', 'w') as f:\n",
    "    f.write(js_code)\n",
    "\n",
    "print(\"Schedule data saved to 'schedule_data.js'\")\n",
    "print(js_code)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
