{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e5290fc5-5d5b-4ab8-80f1-deec67aecf62",
   "metadata": {},
   "outputs": [],
   "source": [
    "from __future__ import annotations\n",
    "\n",
    "import argparse\n",
    "import json\n",
    "from pathlib import Path\n",
    "\n",
    "def parse_csv_to_schedule_data(csv_path: Path) -> list[dict]:\n",
    "    \"\"\"\n",
    "    TODO: Replace this with your real cleaning logic.\n",
    "    Return a list of dicts shaped like:\n",
    "    [{ \"name\": \"Person\", \"Mon\": \"1015AM\", ... }, ...]\n",
    "    \"\"\"\n",
    "\n",
    "    #Import Pandas\n",
    "    import pandas as pd\n",
    "    \n",
    "    #load in from CSV\n",
    "    df = pd.read_csv('Dec15-21_Eataly_Schedule.csv')\n",
    "        \n",
    "\n",
    "    #drop all irrelevant rows at the top\n",
    "    df = df.drop([0,2,3,4])\n",
    "    \n",
    "    #reset indexes\n",
    "    df = df.reset_index(drop=True)\n",
    "\n",
    "def newest_csv(data_dir: Path) -> Path:\n",
    "    csvs = list(data_dir.glob(\"*.csv\"))\n",
    "    if not csvs:\n",
    "        raise FileNotFoundError(f\"No CSV files found in {data_dir}\")\n",
    "    csvs.sort(key=lambda p: p.stat().st_mtime, reverse=True)\n",
    "    return csvs[0]\n",
    "\n",
    "def write_js(out_path: Path, schedule_data: list[dict]) -> None:\n",
    "    out_path.parent.mkdir(parents=True, exist_ok=True)\n",
    "    js = (\n",
    "        \"// AUTO GENERATED FILE. DO NOT EDIT.\\n\"\n",
    "        \"export const scheduleData = \"\n",
    "        + json.dumps(schedule_data, ensure_ascii=False, indent=2)\n",
    "        + \";\\n\"\n",
    "    )\n",
    "    out_path.write_text(js, encoding=\"utf-8\")\n",
    "\n",
    "def main() -> None:\n",
    "    parser = argparse.ArgumentParser()\n",
    "    parser.add_argument(\"--data-dir\", required=True)\n",
    "    parser.add_argument(\"--out\", required=True)\n",
    "    args = parser.parse_args()\n",
    "\n",
    "    data_dir = Path(args.data_dir)\n",
    "    out_path = Path(args.out)\n",
    "\n",
    "    latest_csv = newest_csv(data_dir)\n",
    "    schedule_data = parse_csv_to_schedule_data(latest_csv)\n",
    "    write_js(out_path, schedule_data)\n",
    "\n",
    "    print(f\"Used latest CSV: {latest_csv}\")\n",
    "    print(f\"Wrote JS to: {out_path}\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
